apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-properties
  annotations:
    strategy.spinnaker.io/versioned: "false"
data:
{{ (.Files.Glob "templates/log4j2.properties").AsConfig | indent 2 }}