apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  encryption_keys.yml: |
    encryption:
      active_key_label: bogus-label
      encryption_keys:
      - label: bogus-label
        passphrase: bogus-key