apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uaa-secret
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: uaa-secret
  data:
  - secretKey: uaa.yml
    remoteRef:
      key: uaa-secret
      version: latest