apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-config
  annotations:
    kapp.k14s.io/versioned: ""
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
data:
  uaa.yml: |
    issuer:
      uri: http://localhost:8080/uaa
    LOGIN_SECRET: loginsecret
    database:
      maxactive: 100
      maxidle: 10
      minidle: 0
      removeabandoned: false
      logabandoned: true
      abandonedtimeout: 300
      url: localhost:5432
    smtp:
      host: null
      port: 25
      starttls: null
      from_address: null
      sslprotocols: null
    oauth:
      client:
        override: true
      clients:
        admin:
          authorized-grant-types: client_credentials
          authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
  log4j2.properties: |-
    status = error
    dest = err
    name = UaaLog

    property.log_pattern=[%d{yyyy-MM-dd'T'HH:mm:ss.nnnnnn}{GMT+0}Z] uaa%X{context} - %pid [%t] .... %5p --- %c{1}: %replace{%m}{(?<=password=|client_secret=)([^&]*)}{<redacted>}%n

    appender.uaaDefaultAppender.type = Console
    appender.uaaDefaultAppender.name = UaaDefaultAppender
    appender.uaaDefaultAppender.layout.type = PatternLayout
    appender.uaaDefaultAppender.layout.pattern = [UAA] ${log_pattern}

    appender.uaaAuditAppender.type = Console
    appender.uaaAuditAppender.name = UaaAuditAppender
    appender.uaaAuditAppender.layout.type = PatternLayout
    appender.uaaAuditAppender.layout.pattern = [UAA_AUDIT] ${log_pattern}

    rootLogger.level = info
    rootLogger.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender

    logger.UAAAudit.name = UAA.Audit
    logger.UAAAudit.level = info
    logger.UAAAudit.additivity = true
    logger.UAAAudit.appenderRef.auditEventLog.ref = UaaAuditAppender

    logger.cfIdentity.name = org.cloudfoundry.identity
    logger.cfIdentity.level = info
    logger.cfIdentity.additivity = false
    logger.cfIdentity.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    matchLabels:
      app: uaa-deployment
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: /metrics
      labels:
        app: uaa-deployment
        app.kubernetes.io/name: uaa
        app.kubernetes.io/instance: uaa-standalone
        app.kubernetes.io/version: 74.12.0
        app.kubernetes.io/component: authorization_server
        app.kubernetes.io/part-of: uaa
        app.kubernetes.io/managed-by: kubectl
      namespace: default
    spec:
      serviceAccountName: uaa
      initContainers:
      - name: build-uaa-truststore
        image: cloudfoundry/uaa@sha256:4c7f2d881bc9c4a075232064e906d032c9512b03b87c06cbb2501560cb2f14e4
        command:
        - sh
        - -c
        - |
          find_keytool_or_fail_fast() {
            local has_keytool
            ls "${JAVA_HOME}"/bin/keytool
            has_keytool=$?

            if [ ${has_keytool} -ne 0 ]; then
              exit ${has_keytool}
            fi
          }

          import_cert() {
            local pemfile="${1}"
            local alias="${2}"

            echo "Adding ${pemfile} to truststore"

            # Have to use cat instead of -file
            # because keytool won't understand all of the filenames!
            cat "${pemfile}" | "${JAVA_HOME}"/bin/keytool \
              -noprompt \
              -import \
              -trustcacerts \
              -alias "${alias}" \
              -keystore "${TRUSTSTORE_FILE}" \
              -storepass "${TRUSTSTORE_PASSWORD}"
          }

          get_alias() {
            local pemfile="${1}"
            basename "${pemfile}" .pem
          }

          add_ca_certs() {
            local has_ca_certs
            ls ${SECRETS_DIR}/ca_certs/*.pem
            has_ca_certs=$?

            if [ ${has_ca_certs} -eq 0 ]; then
              for cert in ${SECRETS_DIR}/ca_certs/*.pem; do
                import_cert "${cert}" "$(get_alias $cert)"
              done
            fi
          }

          add_system_certs() {
            for cert in $OS_CERTS_DIR/*.pem; do
              import_cert "${cert}" "$(get_alias $cert)"
            done
          }

          main() {
            find_keytool_or_fail_fast
            add_ca_certs
            add_system_certs
          }

          main
        env:
        - name: SECRETS_DIR
          value: /etc/secrets
        - name: TRUSTSTORE_FILE
          value: /etc/truststore/uaa.pkcs12.truststore
        - name: TRUSTSTORE_PASSWORD
          value: changeit
        - name: JAVA_HOME
          value: /layers/paketo-buildpacks_bellsoft-liberica/jre
        - name: OS_CERTS_DIR
          value: /etc/ssl/certs
        volumeMounts:
        - name: ca-certs-files
          mountPath: /etc/secrets/ca_certs
          readOnly: true
        - name: truststore-file
          mountPath: /etc/truststore
      containers:
      - name: uaa
        image: cloudfoundry/uaa@sha256:4c7f2d881bc9c4a075232064e906d032c9512b03b87c06cbb2501560cb2f14e4
        resources:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 2000Mi
            cpu: 500m
        ports:
        - name: http-uaa
          containerPort: 8080
          protocol: TCP
        env:
        - name: BPL_TOMCAT_ACCESS_LOGGING
          value: "y"
        - name: JAVA_OPTS
          value: -Dspring_profiles=postgresql -Djava.security.egd=file:/dev/./urandom -Dlogging.config=/etc/config/log4j2.properties -Dlog4j.configurationFile=/etc/config/log4j2.properties -DCLOUDFOUNDRY_CONFIG_PATH=/etc/config -DSECRETS_DIR=/etc/secrets -Djavax.net.ssl.trustStore=/etc/truststore/uaa.pkcs12.truststore -Djavax.net.ssl.trustStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=changeit -Dstatsd.enabled=true -Dservlet.session-store=database
        volumeMounts:
        - name: uaa-config
          mountPath: /etc/config
        - name: smtp-credentials-file
          mountPath: /etc/secrets/smtp_credentials.yml
          subPath: smtp_credentials.yml
          readOnly: true
        - name: database-credentials-file
          mountPath: /etc/secrets/database_credentials.yml
          subPath: database_credentials.yml
          readOnly: true
        - name: admin-client-credentials-file
          mountPath: /etc/secrets/admin_client_credentials.yml
          subPath: admin_client_credentials.yml
          readOnly: true
        - name: jwt-policy-signing-keys-file
          mountPath: /etc/secrets/jwt_policy_signing_keys.yml
          subPath: jwt_policy_signing_keys.yml
          readOnly: true
        - name: truststore-file
          mountPath: /etc/truststore
          readOnly: true
        - name: saml-keys-file
          mountPath: /etc/secrets/saml_keys.yml
          subPath: saml_keys.yml
          readOnly: true
        - name: encryption-keys-file
          mountPath: /etc/secrets/encryption_keys.yml
          subPath: encryption_keys.yml
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-uaa
          failureThreshold: 25
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-uaa
      - name: statsd-exporter
        image: cloudfoundry/statsd_exporter:v0.15.0@sha256:10a64dc4ad0a3e3fe88372f0481dea5c02595c38d168617836a99a649d3ac407
        imagePullPolicy: Always
        args:
        - --statsd.listen-udp=:8125
        ports:
        - name: metrics-uaa
          containerPort: 9102
          protocol: TCP
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: uaa-config
        configMap:
          name: uaa-config
      - name: smtp-credentials-file
        secret:
          optional: true
          secretName: uaa-smtp-credentials
      - name: database-credentials-file
        secret:
          optional: true
          secretName: uaa-database-credentials
      - name: admin-client-credentials-file
        secret:
          secretName: uaa-admin-client-credentials
      - name: jwt-policy-signing-keys-file
        secret:
          secretName: uaa-jwt-policy-signing-keys
      - name: ca-certs-files
        secret:
          optional: true
          secretName: uaa-ca-certs
      - name: truststore-file
        emptyDir: {}
      - name: saml-keys-file
        secret:
          optional: false
          secretName: uaa-saml-keys
      - name: encryption-keys-file
        secret:
          optional: false
          secretName: encryption-keys
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-admin-client-credentials
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  admin_client_credentials.yml: |
    oauth:
      clients:
        admin:
          secret: client_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  encryption_keys.yml: |
    encryption:
      active_key_label: bogus-label
      encryption_keys:
      - label: bogus-label
        passphrase: bogus-key
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-jwt-policy-signing-keys
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  jwt_policy_signing_keys.yml: |
    jwt:
      token:
        policy:
          activeKeyId: FAKE_JWT_SIGNING_KEY_DO_NOT_USE
          keys:
            FAKE_JWT_SIGNING_KEY_DO_NOT_USE:
              signingKey: FAKE_SIGNING_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-saml-keys
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  saml_keys.yml: |
    login:
      saml:
        activeKeyId: FAKE_SAML_KEY_ID
        keys:
          FAKE_SAML_KEY_ID:
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIICXQIBAAKBgQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5
              L39WqS9u0hnA+O7MCA/KlrAR4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vA
              fpOwznoD66DDCnQVpbCjtDYWX+x6imxn8HCYxhMol6ZnTbSsFW6VZjFMjQIDAQAB
              AoGAVOj2Yvuigi6wJD99AO2fgF64sYCm/BKkX3dFEw0vxTPIh58kiRP554Xt5ges
              7ZCqL9QpqrChUikO4kJ+nB8Uq2AvaZHbpCEUmbip06IlgdA440o0r0CPo1mgNxGu
              lhiWRN43Lruzfh9qKPhleg2dvyFGQxy5Gk6KW/t8IS4x4r0CQQD/dceBA+Ndj3Xp
              ubHfxqNz4GTOxndc/AXAowPGpge2zpgIc7f50t8OHhG6XhsfJ0wyQEEvodDhZPYX
              kKBnXNHzAkEAyCA76vAwuxqAd3MObhiebniAU3SnPf2u4fdL1EOm92dyFs1JxyyL
              gu/DsjPjx6tRtn4YAalxCzmAMXFSb1qHfwJBAM3qx3z0gGKbUEWtPHcP7BNsrnWK
              vw6By7VC8bk/ffpaP2yYspS66Le9fzbFwoDzMVVUO/dELVZyBnhqSRHoXQcCQQCe
              A2WL8S5o7Vn19rC0GVgu3ZJlUrwiZEVLQdlrticFPXaFrn3Md82ICww3jmURaKHS
              N+l4lnMda79eSp3OMmq9AkA0p79BvYsLshUJJnvbk76pCjR28PK4dV1gSDUEqQMB
              qy45ptdwJLqLJCeNoR0JUcDNIRhOCuOPND7pcMtX6hI/
              -----END RSA PRIVATE KEY-----
            passphrase: password
            certificate: |
              -----BEGIN CERTIFICATE-----
              MIIDSTCCArKgAwIBAgIBADANBgkqhkiG9w0BAQQFADB8MQswCQYDVQQGEwJhdzEO
              MAwGA1UECBMFYXJ1YmExDjAMBgNVBAoTBWFydWJhMQ4wDAYDVQQHEwVhcnViYTEO
              MAwGA1UECxMFYXJ1YmExDjAMBgNVBAMTBWFydWJhMR0wGwYJKoZIhvcNAQkBFg5h
              cnViYUBhcnViYS5hcjAeFw0xNTExMjAyMjI2MjdaFw0xNjExMTkyMjI2MjdaMHwx
              CzAJBgNVBAYTAmF3MQ4wDAYDVQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAM
              BgNVBAcTBWFydWJhMQ4wDAYDVQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAb
              BgkqhkiG9w0BCQEWDmFydWJhQGFydWJhLmFyMIGfMA0GCSqGSIb3DQEBAQUAA4GN
              ADCBiQKBgQDHtC5gUXxBKpEqZTLkNvFwNGnNIkggNOwOQVNbpO0WVHIivig5L39W
              qS9u0hnA+O7MCA/KlrAR4bXaeVVhwfUPYBKIpaaTWFQR5cTR1UFZJL/OF9vAfpOw
              znoD66DDCnQVpbCjtDYWX+x6imxn8HCYxhMol6ZnTbSsFW6VZjFMjQIDAQABo4Ha
              MIHXMB0GA1UdDgQWBBTx0lDzjH/iOBnOSQaSEWQLx1syGDCBpwYDVR0jBIGfMIGc
              gBTx0lDzjH/iOBnOSQaSEWQLx1syGKGBgKR+MHwxCzAJBgNVBAYTAmF3MQ4wDAYD
              VQQIEwVhcnViYTEOMAwGA1UEChMFYXJ1YmExDjAMBgNVBAcTBWFydWJhMQ4wDAYD
              VQQLEwVhcnViYTEOMAwGA1UEAxMFYXJ1YmExHTAbBgkqhkiG9w0BCQEWDmFydWJh
              QGFydWJhLmFyggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEEBQADgYEAYvBJ
              0HOZbbHClXmGUjGs+GS+xC1FO/am2suCSYqNB9dyMXfOWiJ1+TLJk+o/YZt8vuxC
              KdcZYgl4l/L6PxJ982SRhc83ZW2dkAZI4M0/Ud3oePe84k8jm3A7EvH5wi5hvCkK
              RpuRBwn3Ei+jCRouxTbzKPsuCVB+1sNyxMTXzf0=
              -----END CERTIFICATE-----
---
apiVersion: v1
kind: Service
metadata:
  name: uaa
  labels:
    app: uaa-deployment
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http-uaa
    targetPort: 8080
    protocol: TCP
  selector:
    app: uaa-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uaa
  namespace: default
  labels:
    app.kubernetes.io/name: uaa
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/version: 74.12.0
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/managed-by: kubectl
automountServiceAccountToken: false