#Deploy UAA Server as Cloud Foundry Service
---
applications:
- name: uaa-sdx
  memory: 1024M
  instances: 1
  random-route: false
  path: ./target/libs/cloudfoundry-identity-uaa-4.8.3.war
  host: uaa-sdx
  id: admin
  secret: adminsecret
  authorized-grant-types: client_credentials
  scope: none
  authorities: uaa.admin,clients.read,clients.write,clients.secret
  env:
    UAA_URL: http://uaa-SPACE.apps.devtest.onsclofo.uk
    LOGIN_URL: http://uaa-SPACE.apps.devtest.onsclofo.uk
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    UAA_CONFIG_YAML: |
      spring_profiles: default,postgresql
      database:
          driverClassName: org.postgresql.Driver
          url: DB_URL
          username: DB_USERNAME
          password: DB_PASSWORD
          maxactive: 4
          maxidle: 2
          minidle: 1
      login:
        serviceProviderKey: |
          PRIVATE_KEY
        serviceProviderKeyPassword: PRIVATE_KEY_PASSWORD
        serviceProviderCertificate: |
          PUBLIC_KEY_PASSWORD
      jwt:
        token:
          signing-key: tokenKey
      zones:
        internal:
          hostnames:
           - myuaa.bosh-lite.com
