#Deploy UAA Server as Cloud Foundry Service
---
applications:
- name: uaa-SPACE
  memory: 1024M
  instances: 1
  random-route: false
  path: ./target/lib/cloudfoundry-identity-uaa-4.8.3.war
  host: uaa-SPACE
  id: UAA_ID
  secret: UAA_SECRET
  authorized-grant-types: client_credentials
  scope: none
  authorities: uaa.admin,clients.read,clients.write,clients.secret
  env:
    UAA_URL: http://uaa-SPACE.apps.devtest.onsclofo.uk
    LOGIN_URL: http://uaa-SPACE.apps.devtest.onsclofo.uk
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    UAA_CONFIG_YAML: |
      spring_profiles: default,postgresql
      database:
          driverClassName: org.postgresql.Driver
          url: DB_URL
          username: DB_USERNAME
          password: DB_PASSWORD
          maxactive: 4
          maxidle: 2
          minidle: 1
      login:
        serviceProviderKey: |
          PRIVATE_KEY
        serviceProviderKeyPassword: PRIVATE_KEY_PASSWORD
        serviceProviderCertificate: |
          CERTIFICATE
      jwt:
        signing-key: |
            JWT_SIGNING_KEY
        verification-key: |
            JWT_VERIFICATION_KEY
      zones:
        internal:
          hostnames:
           - myuaa.bosh-lite.com

